### ISSUE TITLE
DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead

### ISSUE THREAD

**Issue by doberkofler** [senotrusov/bell-on-bundler-error-plugin#1]
When using the `bell-on-bundler-error-plugin` on webpack 4, the following message is shown:
```
DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
```

[x] I agree that this is the Contribution as defined in Apache License, Version 2.0 (the "License") and I am submitting this Contribution in compliance with the License. A copy of the License can be obtained at http://www.apache.org/licenses/LICENSE-2

**Comment by senotrusov** [comment]
Hello!

Thank you for your time and interest for such a small plugin.

Unfortunately, I don't have much time to deal with that issue right now. Your pull requests are always welcome.
